In [15]:
#fabonacci series
n=int(input("enter range"))
a=0
b=1
for i in range(2,n+1):
    c=a+b
    a=b
    b=c
    print(b)

1


In [24]:
#odd even
a= int(input())
if a>0:
    if a%2==0:
        print(True)
    else:
        print(False)
else:
    print("Wrong input try again !")

False


In [48]:
#leap year
a=int(input("enter year"))
if a%400==0 and a%100==0:
    print(a,"is leap")
elif a%4==0 and a%100!=0:
    print(a, "is leap")
else:
    print(a, "is not leap")

1616 is leap


In [47]:
year = int(input())
if ((year % 400 == 0) and (year % 100 == 0)) or ((year % 4 ==0) and (year % 100 != 0)):
    print("{0} is leap year".format(year)) 
else:
    print("{0} is not a leap year".format(year))

1616 is leap year


In [63]:
#prime number
n=int(input("number upto which want to calculate prime number"))

for i in range(1,n+1):
    if i>1:
        for j in range(2,i):
            if i%j == 0:
                break
        else:
            print(i)


2
3
5
7
11
13
17
19
23


In [86]:
n=int(input("enter number to find prime"))
flag=0
if i>1:
    for i in range(2,n):
        if n%i==0:
            flag=1
if flag==1:
    print(n, "is not prime")
else:
    print(n, "is prime")

31 is prime


In [87]:
import requests

x = requests.get('https://w3schools.com/python/demopage.htm')

print(x.text)

<!DOCTYPE html>
<html>
<body>

<h1>This is a Test Page</h1>

</body>
</html>


In [105]:
print('012'.isdigit())

True


In [109]:
import numpy as np
arr=([1,2,-3,-5,8])
count=0
for i in arr:
    if i<0:
        count=count+1
print(count)


2


In [112]:
import numpy as np
arr =np.ones((3,2)*2,dtype=int)
print(arr)

[[[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]


 [[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]


 [[[1 1]
   [1 1]
   [1 1]]

  [[1 1]
   [1 1]
   [1 1]]]]


In [114]:
import numpy as np
print("Right shift 40 by two positions:", np.right_shift(40,2))

Right shift 40 by two positions: 10


In [116]:
import numpy as np
print(np.char.center('hello',20,fillchar='*'))
print(np.char.capitalize("hello world"))

*******hello********
Hello world


In [4]:
import numpy as np
x1=np.random.randint(10,size=6)
print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 dtype:", x1.dtype)
print(x1)

x1 ndim: 1
x1 shape: (6,)
x1 dtype: int32
[1 8 5 8 1 9]


In [8]:
a=input()
print("Ascii value of '{}' is:".format(a), ord(a))

Ascii value of '%' is: 37


In [83]:
n = int(input())
m = int(input())
for num in range(n, m+1):
    if (num>1):
        for i in range(2, num):
            if(num % i ==0 ):
                break
        else:
            print(num)

2
3
5
7


In [21]:
a = input()
even_count, odd_count = 0, 0 
for num in range(len(a)):
     if num % 2 == 0:
        even_count += 1
     else:
        odd_count += 1
print("Even numbers in the str: ", even_count)
print("Odd numbers in the str: ", odd_count)

Even numbers in the str:  2
Odd numbers in the str:  2


In [85]:
#factorial program
a=int(input())
fact=1
for i in range(1,a+1):
    fact=fact*i
print(fact)

120
